services:
    haivala.entropy.main.listener:
        class: haivala\entropy\event\main_listener
        arguments:
            - '@config'
            - '@user'
            - '@template'
        tags:
            - { name: event.listener }

